/** Textos del brief de /contacto (ES/EN). */
export const briefCopy = {
  es: {
    seo: 'Contacto',
    desc: 'Cuéntanos tu proyecto en cinco pasos breves y te preparamos una propuesta a medida, sin precios de catálogo.',
    title: 'Hablemos.',
    sub: 'Cinco pasos breves. Con ellos preparamos una propuesta a medida, sin precios de catálogo.',
    direct: '¿Prefieres hablar directamente?',
    whatsapp: 'WhatsApp',
    whatsappMsg: 'Hola, os escribo desde la web de NEO Studio.',
    privacyNote: 'Tus datos solo se usan para responderte.',
    privacyLink: 'Política de privacidad',
    step: (n: number, total: number) => `Paso ${n} de ${total}`,
    steps: [
      { title: '¿Qué necesitas?', intro: 'Marca todo lo que encaje. Si aún no lo tienes claro, también vale.' },
      { title: 'Tu marca', intro: 'Lo justo para entender a quién vamos a dirigir.' },
      { title: 'El encargo', intro: 'Qué quieres conseguir y para cuándo.' },
      { title: 'Referencias', intro: 'Opcional. Lo que te gusta nos dice mucho.' },
      { title: 'Cómo hablamos', intro: 'Te respondemos por el canal que prefieras.' },
    ],
    unsure: 'Aún no lo sé',
    unsureHint: 'Te ayudamos a elegir.',
    brand: 'Nombre de la marca',
    link: 'Web o Instagram',
    linkHint: 'Opcional',
    sector: 'Sector',
    goal: 'Objetivo',
    timeline: 'Plazo',
    budget: 'Inversión orientativa',
    budgetHint: 'Opcional. Solo nos ayuda a proponer con sentido.',
    refs: 'Enlaces de referencia',
    refsHint: 'Opcional. Vídeos, webs o perfiles que te gusten, uno por línea.',
    notes: '¿A qué marca te gustaría parecerte?',
    notesHint: (n: number, max: number) => `${n}/${max} caracteres`,
    name: 'Tu nombre',
    email: 'Email',
    phone: 'Teléfono',
    phoneHint: 'Opcional, salvo si prefieres llamada o WhatsApp.',
    pref: 'Prefiero que me contactéis por',
    consentA: 'He leído la ',
    consentLink: 'política de privacidad',
    consentB: ' y acepto que NEO Studio use estos datos para responder a mi solicitud.',
    optional: 'Opcional',
    back: 'Atrás',
    next: 'Continuar',
    submit: 'Enviar brief',
    sending: 'Enviando…',
    draft: 'Hemos recuperado tu borrador.',
    reset: 'Empezar de cero',
    err: {
      services: 'Elige al menos una opción.',
      brand: 'Escribe el nombre de tu marca.',
      sector: 'Elige un sector.',
      goal: 'Elige un objetivo.',
      name: 'Escribe tu nombre.',
      email: 'Escribe tu email.',
      emailFormat: 'Revisa el email: parece incompleto.',
      phone: 'Para llamarte o escribirte por WhatsApp necesitamos un teléfono.',
      consent: 'Necesitamos tu permiso para poder responderte.',
    },
    failTitle: 'No hemos podido enviar el brief.',
    failLine: 'Tu borrador sigue guardado. Envíalo con un clic por otra vía:',
    sendWhatsapp: 'Enviar por WhatsApp',
    sendEmail: 'Enviar por email',
    handoffTitle: (id: string) => `Tu brief ${id} está listo.`,
    handoffWhatsapp: 'Hemos abierto WhatsApp con el resumen. Solo falta que pulses enviar.',
    handoffEmail: 'Hemos abierto tu correo con el resumen. Solo falta que lo envíes.',
    handoffAgain: 'Abrir de nuevo',
    handoffBack: 'Volver al formulario',
    pending: 'El envío del formulario está pendiente de configurar. Mientras tanto, escríbenos por las vías de contacto del pie de página.',
  },
  en: {
    seo: 'Contact',
    desc: 'Tell us about your project in five short steps and we will prepare a tailored proposal, with no catalogue prices.',
    title: 'Let’s talk.',
    sub: 'Five short steps. With them we prepare a tailored proposal, with no catalogue prices.',
    direct: 'Rather talk directly?',
    whatsapp: 'WhatsApp',
    whatsappMsg: 'Hi, I’m writing from the NEO Studio website.',
    privacyNote: 'Your details are only used to reply to you.',
    privacyLink: 'Privacy policy',
    step: (n: number, total: number) => `Step ${n} of ${total}`,
    steps: [
      { title: 'What do you need?', intro: 'Tick everything that fits. Not sure yet? That works too.' },
      { title: 'Your brand', intro: 'Just enough to understand who we will be directing.' },
      { title: 'The brief', intro: 'What you want to achieve, and by when.' },
      { title: 'References', intro: 'Optional. What you like tells us a lot.' },
      { title: 'How we talk', intro: 'We reply through the channel you prefer.' },
    ],
    unsure: 'Not sure yet',
    unsureHint: 'We will help you choose.',
    brand: 'Brand name',
    link: 'Website or Instagram',
    linkHint: 'Optional',
    sector: 'Sector',
    goal: 'Goal',
    timeline: 'Timeline',
    budget: 'Approximate budget',
    budgetHint: 'Optional. It only helps us propose something that makes sense.',
    refs: 'Reference links',
    refsHint: 'Optional. Videos, websites or profiles you like, one per line.',
    notes: 'Which brand would you like to look like?',
    notesHint: (n: number, max: number) => `${n}/${max} characters`,
    name: 'Your name',
    email: 'Email',
    phone: 'Phone',
    phoneHint: 'Optional, unless you prefer a call or WhatsApp.',
    pref: 'I’d rather you contact me by',
    consentA: 'I have read the ',
    consentLink: 'privacy policy',
    consentB: ' and agree that NEO Studio may use these details to reply to my request.',
    optional: 'Optional',
    back: 'Back',
    next: 'Continue',
    submit: 'Send brief',
    sending: 'Sending…',
    draft: 'We have restored your draft.',
    reset: 'Start over',
    err: {
      services: 'Choose at least one option.',
      brand: 'Enter your brand’s name.',
      sector: 'Choose a sector.',
      goal: 'Choose a goal.',
      name: 'Enter your name.',
      email: 'Enter your email.',
      emailFormat: 'Check the email: it looks incomplete.',
      phone: 'To call you or message you on WhatsApp we need a phone number.',
      consent: 'We need your permission to reply to you.',
    },
    failTitle: 'We couldn’t send the brief.',
    failLine: 'Your draft is still saved. Send it with one click another way:',
    sendWhatsapp: 'Send via WhatsApp',
    sendEmail: 'Send by email',
    handoffTitle: (id: string) => `Your brief ${id} is ready.`,
    handoffWhatsapp: 'We have opened WhatsApp with the summary. All that is left is to press send.',
    handoffEmail: 'We have opened your email with the summary. All that is left is to send it.',
    handoffAgain: 'Open again',
    handoffBack: 'Back to the form',
    pending: 'Form delivery is still being set up. In the meantime, reach us through the contact details in the footer.',
  },
}

export type BriefCopy = (typeof briefCopy)['es']
export type ErrKey = keyof BriefCopy['err']
