import type { CSSProperties } from 'react'
import type { CaseKind } from '@/content/cases'
import type { ServiceId } from '@/content/services'

/** Nombre del servicio tal como se lee dentro de una frase (minúscula salvo siglas). */
const waService: Record<'es' | 'en', Record<ServiceId, string>> = {
  es: {
    'ai-video': 'vídeo con IA',
    'ai-3d': '3D con IA',
    websites: 'webs de autor',
    editing: 'postproducción',
    content: 'contenido para redes',
    'mobile-cinema': 'cine con el móvil',
  },
  en: {
    'ai-video': 'AI video',
    'ai-3d': 'AI 3D',
    websites: 'signature website',
    editing: 'post-production',
    content: 'social content',
    'mobile-cinema': 'mobile cinema',
  },
}

/** Textos de interfaz de la plantilla de servicio. */
export const ui = {
  es: {
    localNav: 'Secciones del servicio',
    sections: 'Secciones',
    overview: 'Resumen',
    process: 'Proceso',
    examples: 'Ejemplos',
    faq: 'Preguntas',
    propose: 'Solicitar propuesta',
    proposeShort: 'Propuesta',
    ai: 'Generado con IA, dirigido por NEO',
    processTitle: 'Así trabajamos.',
    verbs: ['Brief', 'Dirección', 'Producción', 'Entrega'],
    deliverables: 'Entregables',
    examplesTitle: 'Trabajos para clientes.',
    examplesText: 'Encargos reales, hechos para marcas que confiaron en la casa.',
    examplesTitleMixed: 'Trabajo de la casa.',
    examplesTextMixed: 'Encargos de clientes y piezas propias, cada una con su etiqueta.',
    seeWork: 'Ver trabajo',
    seeCase: 'Ver caso',
    specs: 'Ficha técnica.',
    faqTitle: 'Lo que suelen preguntarnos.',
    pairs: 'Combina con',
    discover: 'Descubrir',
    kind: { client: 'Encargo de cliente', study: 'Estudio propio', concept: 'Concepto · no oficial', own: 'Producto propio' } satisfies Record<CaseKind, string>,
    frame: 'Fotograma',
    startFrame: 'Fotograma inicial',
    endFrame: 'Fotograma final',
    compare: 'Comparar el primer fotograma con el último',
    log: 'Log',
    graded: 'Etalonado',
    logCompare: 'Comparar la imagen en Log con la imagen etalonada',
    simulation: 'Simulación',
    cutsGroup: 'Montaje',
    scenesGroup: 'Uso',
    script: 'Guion',
    scriptHint: 'Toca una línea para saltar a ese momento.',
    visit: 'Visitar web',
    newTab: 'se abre en una pestaña nueva',
    alsoOurs: 'También de la casa',
    gridOn: 'Ver la rejilla',
    gridOff: 'Ocultar la rejilla',
    typeScale: 'Escala tipográfica',
    curve: 'Curva de movimiento',
    setting: 'Ajuste',
    value: 'Valor',
    whatsapp: 'WhatsApp',
    /** Mensaje prellenado de WhatsApp: el servicio en minúscula dentro de la frase (con sus siglas) */
    whatsappMsg: (id: ServiceId) => `Hola, me interesa vuestro servicio de ${waService.es[id]}.`,
    notFoundTitle: 'Este servicio no existe.',
    notFoundText: 'Puede que el enlace haya cambiado. Estos son los seis oficios de la casa.',
    allServices: 'Ver servicios',
  },
  en: {
    localNav: 'Service sections',
    sections: 'Sections',
    overview: 'Overview',
    process: 'Process',
    examples: 'Examples',
    faq: 'Questions',
    propose: 'Request a proposal',
    proposeShort: 'Proposal',
    ai: 'AI-generated, directed by NEO',
    processTitle: 'How we work.',
    verbs: ['Brief', 'Direction', 'Production', 'Delivery'],
    deliverables: 'Deliverables',
    examplesTitle: 'Client work.',
    examplesText: 'Real commissions, made for brands that trusted the house.',
    examplesTitleMixed: 'Work from the house.',
    examplesTextMixed: 'Client commissions and our own pieces, each one labelled.',
    seeWork: 'See work',
    seeCase: 'See case',
    specs: 'Specifications.',
    faqTitle: 'What people usually ask.',
    pairs: 'Pairs well with',
    discover: 'Discover',
    kind: { client: 'Client commission', study: 'Studio piece', concept: 'Concept · unofficial', own: 'Own product' } satisfies Record<CaseKind, string>,
    frame: 'Frame',
    startFrame: 'Start frame',
    endFrame: 'End frame',
    compare: 'Compare the first frame with the last',
    log: 'Log',
    graded: 'Graded',
    logCompare: 'Compare the Log image with the graded image',
    simulation: 'Simulation',
    cutsGroup: 'Cut',
    scenesGroup: 'Use',
    script: 'Script',
    scriptHint: 'Tap a line to jump to that moment.',
    visit: 'Visit website',
    newTab: 'opens in a new tab',
    alsoOurs: 'Also from the house',
    gridOn: 'Show the grid',
    gridOff: 'Hide the grid',
    typeScale: 'Type scale',
    curve: 'Motion curve',
    setting: 'Setting',
    value: 'Value',
    whatsapp: 'WhatsApp',
    whatsappMsg: (id: ServiceId) => `Hi, I’m interested in your ${waService.en[id]} service.`,
    notFoundTitle: 'This service doesn’t exist.',
    notFoundText: 'The link may have changed. These are the six crafts of the house.',
    allServices: 'See services',
  },
}

/** Hairline discontinua superior (detalle Oryzo), como estilo en línea para no tocar el CSS global. */
export const dashedTop: CSSProperties = {
  backgroundImage: 'linear-gradient(to right, var(--color-line-strong) 50%, transparent 0)',
  backgroundSize: '6px 1px',
  backgroundRepeat: 'repeat-x',
  backgroundPosition: 'left top',
}

/**
 * Titular display en columna lateral (4–6 de 12): un escalón por debajo de type-display en escritorio
 * para que los titulares cortos no caigan una palabra por línea.
 */
export const displaySide = 'type-display lg:[font-size:clamp(2.5rem,3.8vw,3.5rem)]'
