
INSERT INTO exercise_catalog (name, slug, description, tips, video_url, primary_muscle_id, difficulty, is_compound)
VALUES
-- Deadlift group → Isquiotibiales Bíceps Femoral
('Peso muerto rumano con barra', 'peso-muerto-rumano-con-barra', 'Patrón de bisagra de cadera con barra orientado al trabajo de isquiotibiales, glúteo mayor y erectores espinales, manteniendo una flexión de rodilla limitada para enfatizar la extensión de cadera.', ARRAY['Desplaza la cadera hacia atrás', 'Mantén la barra próxima al cuerpo', 'Conserva la columna neutra durante todo el recorrido'], 'https://vimeo.com/1174359915', 'f75fa297-0990-49b8-b03a-3777d75b5f4b', 'intermediate', true),

('Peso muerto rumano con mancuernas', 'peso-muerto-rumano-con-mancuernas-1', 'Variante de peso muerto rumano con mancuernas orientada al trabajo de la cadena posterior, permitiendo una trayectoria más libre y adaptable a la movilidad individual.', ARRAY['Lleva las mancuernas cerca de las piernas', 'Mantén una ligera flexión de rodilla', 'Desciende solo hasta donde puedas conservar la pelvis y la columna estables'], 'https://vimeo.com/1174359793', 'f75fa297-0990-49b8-b03a-3777d75b5f4b', 'intermediate', true),

('Peso muerto rumano con mancuernas', 'peso-muerto-rumano-con-mancuernas-2', 'Variante de peso muerto rumano con mancuernas orientada al trabajo de la cadena posterior, permitiendo una trayectoria más libre y adaptable a la movilidad individual.', ARRAY['Lleva las mancuernas cerca de las piernas', 'Mantén una ligera flexión de rodilla', 'Desciende solo hasta donde puedas conservar la pelvis y la columna estables'], 'https://vimeo.com/1174359762', 'f75fa297-0990-49b8-b03a-3777d75b5f4b', 'intermediate', true),

('Peso muerto rumano en máquina', 'peso-muerto-rumano-en-maquina-1', 'Peso muerto rumano en máquina orientado al trabajo de isquiotibiales y glúteos mediante una bisagra de cadera guiada, con una mecánica más estable y reproducible.', ARRAY['Mantén el pecho abierto', 'Desplaza la cadera hacia atrás de forma controlada', 'Evita redondear la zona lumbar al final de la bajada'], 'https://vimeo.com/1174359887', 'f75fa297-0990-49b8-b03a-3777d75b5f4b', 'beginner', true),

('Peso muerto rumano en máquina', 'peso-muerto-rumano-en-maquina-2', 'Peso muerto rumano en máquina orientado al trabajo de isquiotibiales y glúteos mediante una bisagra de cadera guiada, con una mecánica más estable y reproducible.', ARRAY['Mantén el pecho abierto', 'Desplaza la cadera hacia atrás de forma controlada', 'Evita redondear la zona lumbar al final de la bajada'], 'https://vimeo.com/1174359736', 'f75fa297-0990-49b8-b03a-3777d75b5f4b', 'beginner', true),

('Peso muerto con barra', 'peso-muerto-con-barra-1', 'Patrón de peso muerto convencional con barra orientado al trabajo global de la cadena posterior y del tren inferior, con participación relevante de glúteos, isquiotibiales, cuádriceps y musculatura extensora del raquis.', ARRAY['Acerca la barra al cuerpo', 'Genera tensión antes de despegarla del suelo', 'Extiende cadera y rodillas de forma coordinada sin perder la neutralidad lumbar'], 'https://vimeo.com/1174359831', 'f75fa297-0990-49b8-b03a-3777d75b5f4b', 'intermediate', true),

('Peso muerto con barra', 'peso-muerto-con-barra-2', 'Patrón de peso muerto convencional con barra orientado al trabajo global de la cadena posterior y del tren inferior, con participación relevante de glúteos, isquiotibiales, cuádriceps y musculatura extensora del raquis.', ARRAY['Acerca la barra al cuerpo', 'Genera tensión antes de despegarla del suelo', 'Extiende cadera y rodillas de forma coordinada sin perder la neutralidad lumbar'], 'https://vimeo.com/1174359709', 'f75fa297-0990-49b8-b03a-3777d75b5f4b', 'intermediate', true),

-- Calves → Gastrocnemio
('Gemelo en máquina', 'gemelo-en-maquina-1', 'Elevación plantar en máquina orientada al trabajo del gastrocnemio y sóleo, con una ejecución guiada que permite aplicar tensión de forma estable durante todo el recorrido.', ARRAY['Realiza una extensión plantar completa', 'Desciende de forma controlada hasta un estiramiento tolerable', 'Evita rebotar en la parte baja'], 'https://vimeo.com/1174025123', '1f0aaac8-9ca0-4bd6-83e1-b9362952df7c', 'beginner', false),

('Gemelo en multipower', 'gemelo-en-multipower', 'Elevación plantar en multipower orientada al trabajo del tríceps sural con una trayectoria guiada y estable, adecuada para progresar la carga con control.', ARRAY['Coloca el apoyo del pie de forma que permita un buen rango de movimiento', 'Extiende el tobillo de forma completa', 'Evita flexionar excesivamente las rodillas si buscas mayor implicación del gastrocnemio'], 'https://vimeo.com/1174025093', '1f0aaac8-9ca0-4bd6-83e1-b9362952df7c', 'beginner', false),

('Gemelo en máquina', 'gemelo-en-maquina-2', 'Elevación plantar en máquina orientada al trabajo de la musculatura flexora plantar del tobillo, con énfasis sobre el tríceps sural y una mecánica estable y reproducible.', ARRAY['Mantén el recorrido completo', 'Controla la fase excéntrica', 'Evita acelerar el cambio de dirección en la parte baja'], 'https://vimeo.com/1174025072', '1f0aaac8-9ca0-4bd6-83e1-b9362952df7c', 'beginner', false),

-- Abductors → Glúteo Medio
('Abductor', 'abductor-en-maquina', 'Abducción de cadera en máquina orientada al trabajo del glúteo medio, glúteo menor y fibras superiores del glúteo mayor, con una ejecución guiada que facilita aislar el movimiento en el plano frontal.', ARRAY['Mantén la pelvis estable sobre el asiento', 'Evita impulsarte con el tronco', 'Controla tanto la apertura como el retorno para conservar tensión continua'], 'https://vimeo.com/1174024344', '616fdd99-e1d2-4f1a-9297-bba698f9494d', 'beginner', false),

-- Glutes → Glúteo Mayor
('Glúteo medio en polea', 'gluteo-medio-en-polea', 'Abducción de cadera en polea orientada al trabajo del glúteo medio y glúteo menor, con una línea de tracción que mantiene tensión continua durante todo el recorrido.', ARRAY['Mantén la pelvis estable', 'Evita inclinar el tronco para ganar rango', 'Ejecuta la apertura de forma controlada sin balanceo'], 'https://vimeo.com/1174023535', 'a9dc9a28-143e-4716-a5f1-979cd07de4b5', 'intermediate', false),

('Glúteo medio en polea diagonal', 'gluteo-medio-en-polea-diagonal', 'Variante de abducción de cadera en polea con trayectoria diagonal, orientada al glúteo medio y a la musculatura abductora de la cadera mediante un vector de resistencia distinto al plano puramente lateral.', ARRAY['Estabiliza bien la pelvis', 'Dirige el movimiento en la diagonal pautada sin rotar la cadera', 'Controla la fase excéntrica para no perder tensión'], 'https://vimeo.com/1174023461', 'a9dc9a28-143e-4716-a5f1-979cd07de4b5', 'intermediate', false),

('Glúteo medio en máquina', 'gluteo-medio-en-maquina', 'Abducción de cadera en máquina orientada al trabajo del glúteo medio, glúteo menor y fibras superiores del glúteo mayor, con una ejecución guiada que facilita aislar el movimiento.', ARRAY['Mantén la pelvis bien apoyada', 'Evita impulsarte con el tronco', 'Controla tanto la apertura como el retorno para conservar tensión continua'], 'https://vimeo.com/1174023520', 'a9dc9a28-143e-4716-a5f1-979cd07de4b5', 'beginner', false),

('Patada de glúteo en polea', 'patada-de-gluteo-en-polea', 'Extensión de cadera en polea orientada al trabajo del glúteo mayor, con una línea de tracción que mantiene tensión continua durante todo el recorrido.', ARRAY['Mantén la pelvis estable', 'Evita arquear la zona lumbar para ganar rango', 'Empuja hacia atrás con control sin rotar la cadera'], 'https://vimeo.com/1174024038', 'a9dc9a28-143e-4716-a5f1-979cd07de4b5', 'intermediate', false),

('Extensión en polea', 'extension-gluteo-en-polea', 'Variante de extensión de cadera en polea enfocada en el glúteo mayor, útil para trabajar la cadera con un patrón analítico y una resistencia constante.', ARRAY['Estabiliza el tronco', 'Mantén una ligera flexión de la rodilla de apoyo', 'Evita compensar con movimiento lumbar'], 'https://vimeo.com/1174023949', 'a9dc9a28-143e-4716-a5f1-979cd07de4b5', 'intermediate', false),

('Extensión en máquina', 'extension-gluteo-en-maquina', 'Extensión de cadera en máquina orientada al glúteo mayor, con una mecánica guiada que facilita una ejecución estable y reproducible.', ARRAY['Mantén el apoyo firme del tronco', 'Dirige el empuje desde la cadera', 'Evita acelerar el retorno para no perder tensión'], 'https://vimeo.com/1174023979', 'a9dc9a28-143e-4716-a5f1-979cd07de4b5', 'beginner', false),

('Sentadilla búlgara con mancuerna en banco', 'sentadilla-bulgara-con-mancuerna-en-banco', 'Sentadilla búlgara con mancuerna en banco orientada al trabajo unilateral de glúteo mayor y cuádriceps, con alta demanda de estabilidad sobre cadera y rodilla.', ARRAY['Inclina ligeramente el tronco si buscas mayor énfasis en glúteo', 'Coloca el pie delantero a una distancia adecuada', 'Desciende con control sin colapsar la rodilla'], 'https://vimeo.com/1174023913', 'a9dc9a28-143e-4716-a5f1-979cd07de4b5', 'intermediate', true),

('Patada de glúteo con banco', 'patada-de-gluteo-con-banco', 'Patada de glúteo con banco orientada a la extensión de cadera con apoyo externo, facilitando una ejecución más estable y un trabajo focalizado del glúteo mayor.', ARRAY['Mantén la pelvis alineada', 'Evita arquear la zona lumbar', 'Completa la extensión sin impulsarte con el tronco'], 'https://vimeo.com/1174023889', 'a9dc9a28-143e-4716-a5f1-979cd07de4b5', 'beginner', false),

('Extensión de cadera en polea', 'extension-de-cadera-en-polea', 'Extensión de cadera en polea orientada al trabajo analítico del glúteo mayor, manteniendo tensión constante durante la fase concéntrica y excéntrica.', ARRAY['Fija bien la pelvis', 'No abras la cadera durante el gesto', 'Controla la vuelta sin perder la alineación'], 'https://vimeo.com/1174023864', 'a9dc9a28-143e-4716-a5f1-979cd07de4b5', 'intermediate', false),

('Hip thrust', 'hip-thrust', 'Hip thrust orientado al trabajo dominante de extensión de cadera, con énfasis en glúteo mayor y alta capacidad de producción de fuerza en la parte final del recorrido.', ARRAY['Apoya la zona escapular de forma estable', 'Mantén la barbilla ligeramente recogida', 'Extiende la cadera sin hiperextender la zona lumbar'], 'https://vimeo.com/1174023796', 'a9dc9a28-143e-4716-a5f1-979cd07de4b5', 'intermediate', true),

('Hip thrust en multipower', 'hip-thrust-en-multipower', 'Hip thrust en multipower orientado al glúteo mayor mediante una trayectoria guiada que facilita estabilidad y progresión de carga.', ARRAY['Coloca los pies a una distancia que permita una extensión de cadera eficiente', 'Mantén el abdomen activo', 'Bloquea arriba con control sin arquear la espalda'], 'https://vimeo.com/1174023748', 'a9dc9a28-143e-4716-a5f1-979cd07de4b5', 'beginner', true),

('Hiperextensiones', 'hiperextensiones', 'Hiperextensiones orientadas al trabajo de la cadena posterior, con énfasis en glúteo mayor e isquiotibiales según la técnica empleada.', ARRAY['Inicia el movimiento desde la cadera', 'Mantén la columna neutra', 'Evita subir más allá de la alineación natural del tronco'], 'https://vimeo.com/1174023770', 'a9dc9a28-143e-4716-a5f1-979cd07de4b5', 'beginner', true),

('Sentadilla búlgara en multipower', 'sentadilla-bulgara-en-multipower', 'Sentadilla búlgara en multipower orientada al trabajo unilateral de glúteo mayor y cuádriceps, con una trayectoria más estable que la versión libre.', ARRAY['Coloca el pie delantero a una distancia útil', 'Inclina ligeramente el tronco si buscas más estímulo sobre glúteo', 'Controla la bajada sin perder alineación'], 'https://vimeo.com/1174023659', 'a9dc9a28-143e-4716-a5f1-979cd07de4b5', 'intermediate', true),

('Prensa enfoque glúteo mayor', 'prensa-enfoque-gluteo-mayor', 'Prensa con enfoque en glúteo mayor orientada al trabajo dominante de cadera mediante una colocación específica de los pies que modifica la distribución de cargas del gesto.', ARRAY['Coloca los pies en una posición que favorezca la extensión de cadera según la máquina', 'Mantén la pelvis estable', 'Evita acortar el recorrido'], 'https://vimeo.com/1174023631', 'a9dc9a28-143e-4716-a5f1-979cd07de4b5', 'beginner', true),

('Subida al cajón con polea', 'subida-al-cajon-con-polea', 'Subida al cajón con polea orientada al trabajo unilateral de glúteo mayor y cuádriceps, combinando extensión de cadera y rodilla con resistencia adicional.', ARRAY['Impulsa el movimiento con la pierna que sube al cajón', 'Evita empujarte en exceso con la pierna retrasada', 'Controla la bajada para mantener estabilidad'], 'https://vimeo.com/1174023599', 'a9dc9a28-143e-4716-a5f1-979cd07de4b5', 'intermediate', true),

-- Abs → Recto Abdominal
('Crunch abdominal en polea con banco', 'crunch-abdominal-en-polea-con-banco-1', 'Crunch abdominal en polea con banco orientado al trabajo del recto abdominal mediante flexión controlada del tronco, con una resistencia externa que mantiene tensión durante todo el recorrido.', ARRAY['Inicia el gesto desde la columna torácica y lumbar', 'Evita tirar con los brazos', 'Controla la vuelta sin perder la activación abdominal'], 'https://vimeo.com/1174359399', 'fb13aca1-7243-487d-84aa-3b6ddf9363a8', 'intermediate', false),

('Elevaciones de piernas', 'elevaciones-de-piernas', 'Elevaciones de piernas orientadas al trabajo del recto abdominal con participación relevante de los flexores de cadera, especialmente cuando se realizan con el tronco estable y la pelvis en retroversión al final del gesto.', ARRAY['Evita balancear las piernas', 'Lleva la pelvis en retroversión en la parte alta', 'Controla la bajada para no perder tensión'], 'https://vimeo.com/1174359376', 'fb13aca1-7243-487d-84aa-3b6ddf9363a8', 'intermediate', false),

('Crunch abdominal en máquina', 'crunch-abdominal-en-maquina-1', 'Crunch abdominal en máquina orientado al recto abdominal mediante una flexión guiada del tronco, con una mecánica estable y reproducible que facilita la aplicación de carga.', ARRAY['Ajusta la máquina a tu antropometría', 'Inicia el movimiento desde el abdomen', 'Evita empujar con brazos o cadera para completar el recorrido'], 'https://vimeo.com/1174359357', 'fb13aca1-7243-487d-84aa-3b6ddf9363a8', 'beginner', false),

('Crunch abdominal en máquina', 'crunch-abdominal-en-maquina-2', 'Crunch abdominal en máquina orientado al recto abdominal mediante una flexión guiada del tronco, con una mecánica estable y reproducible que facilita la aplicación de carga.', ARRAY['Ajusta la máquina a tu antropometría', 'Inicia el movimiento desde el abdomen', 'Evita empujar con brazos o cadera para completar el recorrido'], 'https://vimeo.com/1174359206', 'fb13aca1-7243-487d-84aa-3b6ddf9363a8', 'beginner', false),

('Crunch abdominal en polea', 'crunch-abdominal-en-polea', 'Crunch abdominal en polea orientado al trabajo del recto abdominal con tensión continua y posibilidad de ajustar la resistencia de forma precisa.', ARRAY['Mantén la pelvis estable', 'Flexiona la columna de forma progresiva', 'Evita convertir el gesto en una simple bajada de brazos'], 'https://vimeo.com/1174359339', 'fb13aca1-7243-487d-84aa-3b6ddf9363a8', 'intermediate', false),

('Crunch abdominal en banco con polea', 'crunch-abdominal-en-banco-con-polea', 'Crunch abdominal en banco con polea orientado a la flexión del tronco contra resistencia externa, enfatizando el recto abdominal durante todo el recorrido.', ARRAY['Fija bien la postura sobre el banco', 'Dirige el gesto desde el abdomen', 'Controla la fase excéntrica para mantener tensión continua'], 'https://vimeo.com/1174359302', 'fb13aca1-7243-487d-84aa-3b6ddf9363a8', 'intermediate', false),

('Crunch abdominal en banco tumbado', 'crunch-abdominal-en-banco-tumbado', 'Crunch abdominal en banco tumbado orientado al recto abdominal mediante flexión del tronco en un patrón simple y controlado, con menor complejidad técnica que las variantes con polea o máquina.', ARRAY['Eleva el tronco desde la musculatura abdominal', 'Evita tirar del cuello con las manos', 'Desciende de forma controlada sin relajarte por completo en la parte baja'], 'https://vimeo.com/1174359247', 'fb13aca1-7243-487d-84aa-3b6ddf9363a8', 'beginner', false);
