INSERT INTO public.exercise_catalog (name, slug, description, primary_muscle_id, difficulty, video_url, equipment, tips, is_compound)
VALUES
  ('Jalón pecho agarre neutro', 'jalon-pecho-agarre-neutro',
   'Tracción vertical que prioriza dorsal ancho y espalda alta con una posición de hombro más cómoda.',
   'ebdff97d-cc4a-4046-b15b-8d0464608341', 'intermediate',
   'https://vimeo.com/1174012733',
   ARRAY['polea', 'agarre neutro'],
   ARRAY['Lleva el agarre al pecho alto', 'No te balancees', 'Mantén los codos orientados hacia abajo'],
   true),

  ('Jalón agarre MAG', 'jalon-agarre-mag',
   'Jalón vertical con agarre MAG para mejorar la activación de la espalda y reducir la tensión en antebrazos.',
   'ebdff97d-cc4a-4046-b15b-8d0464608341', 'intermediate',
   'https://vimeo.com/1174012718',
   ARRAY['polea', 'agarre MAG'],
   ARRAY['Inicia el movimiento con depresión escapular', 'Controla la subida', 'Evita encoger trapecios'],
   true),

  ('Remo alto en polea', 'remo-alto-en-polea',
   'Tracción alta enfocada en trapecio, romboides y deltoide posterior.',
   'ebdff97d-cc4a-4046-b15b-8d0464608341', 'intermediate',
   'https://vimeo.com/1174012690',
   ARRAY['polea'],
   ARRAY['Mantén los codos altos', 'Controla el retorno', 'No cierres demasiado los hombros al final'],
   true),

  ('Remo agarre cerrado polea', 'remo-agarre-cerrado-polea',
   'Remo en polea con agarre cerrado que enfatiza dorsal, trapecio medio y romboides.',
   'ebdff97d-cc4a-4046-b15b-8d0464608341', 'intermediate',
   'https://vimeo.com/117401267',
   ARRAY['polea', 'agarre cerrado'],
   ARRAY['No uses impulso lumbar', 'Mantén tensión continua', 'Termina con buena retracción escapular'],
   true),

  ('Jalón al pecho', 'jalon-al-pecho',
   'Jalón clásico para desarrollar dorsal ancho, redondo mayor y musculatura auxiliar de la espalda.',
   'ebdff97d-cc4a-4046-b15b-8d0464608341', 'beginner',
   'https://vimeo.com/1174012651',
   ARRAY['polea', 'barra larga'],
   ARRAY['Baja la barra al pecho con control', 'Evita tirar detrás de la nuca', 'No arquees en exceso la espalda'],
   true),

  ('Remo en polea espalda alta', 'remo-en-polea-espalda-alta',
   'Remo dirigido a la espalda alta, con mayor énfasis en trapecio, romboides y deltoide posterior.',
   'ebdff97d-cc4a-4046-b15b-8d0464608341', 'intermediate',
   'https://vimeo.com/1174012619',
   ARRAY['polea'],
   ARRAY['Tira hacia la parte alta del torso', 'Abre ligeramente los codos', 'Evita perder tensión escapular'],
   true),

  ('Remo en banco con barra', 'remo-en-banco-con-barra',
   'Remo con apoyo en banco que reduce la carga lumbar y permite focalizar el trabajo en la espalda.',
   'ebdff97d-cc4a-4046-b15b-8d0464608341', 'intermediate',
   'https://vimeo.com/1174012576',
   ARRAY['barra', 'banco'],
   ARRAY['Mantén apoyo firme', 'Controla la barra en todo momento', 'Busca un recorrido completo'],
   true),

  ('Remo bajo en máquina', 'remo-bajo-en-maquina',
   'Tracción horizontal guiada para trabajar dorsal ancho y espalda media con mayor estabilidad.',
   'c314ffe9-6da9-4f10-bb61-fee98a7d4ca9', 'beginner',
   'https://vimeo.com/1174012554',
   ARRAY['máquina'],
   ARRAY['Controla la escápula', 'Evita la extensión lumbar excesiva', 'Termina cada repetición con tensión real'],
   true),

  ('Remo unilateral en máquina', 'remo-unilateral-en-maquina',
   'Variante unilateral guiada que mejora el trabajo individual del dorsal y ayuda a corregir desequilibrios.',
   'c314ffe9-6da9-4f10-bb61-fee98a7d4ca9', 'intermediate',
   'https://vimeo.com/1174012521',
   ARRAY['máquina'],
   ARRAY['No gires el tronco', 'Mantén el hombro controlado', 'Lleva el codo hacia atrás y abajo'],
   false),

  ('Remo en máquina', 'remo-en-maquina',
   'Remo en máquina para desarrollar el dorsal y la espalda media con una técnica estable y reproducible.',
   'c314ffe9-6da9-4f10-bb61-fee98a7d4ca9', 'beginner',
   'https://vimeo.com/1174012496',
   ARRAY['máquina'],
   ARRAY['Mantén el pecho abierto', 'Evita encoger hombros', 'Controla tanto la subida como la bajada'],
   true),

  ('Remo alto en máquina supino', 'remo-alto-en-maquina-supino',
   'Remo alto con agarre supino que incrementa la implicación del dorsal ancho y flexores del codo.',
   'c314ffe9-6da9-4f10-bb61-fee98a7d4ca9', 'intermediate',
   'https://vimeo.com/1174012482',
   ARRAY['máquina'],
   ARRAY['Mantén el pecho alto', 'Evita elevar hombros', 'Busca un recorrido limpio sin impulso'],
   true),

  ('Jalón en máquina unilateral', 'jalon-en-maquina-unilateral',
   'Tracción vertical unilateral enfocada en dorsal ancho, muy útil para mejorar control y simetría.',
   'c314ffe9-6da9-4f10-bb61-fee98a7d4ca9', 'intermediate',
   'https://vimeo.com/1174012451',
   ARRAY['máquina'],
   ARRAY['Inicia con depresión escapular', 'No inclines el torso', 'Lleva el brazo hacia abajo con control'],
   false),

  ('Remo alto en máquina unilateral', 'remo-alto-en-maquina-unilateral',
   'Variante unilateral de tracción horizontal alta, dirigida al dorsal y a la espalda alta con mayor precisión técnica.',
   'c314ffe9-6da9-4f10-bb61-fee98a7d4ca9', 'intermediate',
   'https://vimeo.com/1174012410',
   ARRAY['máquina'],
   ARRAY['Mantén el tronco estable', 'Controla la trayectoria del codo', 'Evita compensar con rotación'],
   false),

  ('Jalón en máquina', 'jalon-en-maquina',
   'Tracción vertical guiada para desarrollar dorsal ancho y musculatura accesoria de la espalda.',
   'c314ffe9-6da9-4f10-bb61-fee98a7d4ca9', 'beginner',
   'https://vimeo.com/1174012371',
   ARRAY['máquina'],
   ARRAY['Saca pecho', 'Baja el agarre con control', 'No conviertas el movimiento en un tirón de brazos'],
   true),

  ('Jalón en máquina discos', 'jalon-en-maquina-discos',
   'Tracción vertical guiada que enfatiza el dorsal ancho mediante una resistencia por discos, favoreciendo una ejecución estable y progresiva.',
   'c314ffe9-6da9-4f10-bb61-fee98a7d4ca9', 'beginner',
   'https://vimeo.com/1174012336',
   ARRAY['máquina', 'discos'],
   ARRAY['Inicia con depresión escapular', 'Saca pecho', 'Evita balancear el tronco'],
   true),

  ('Remo alto en máquina AC', 'remo-alto-en-maquina-ac',
   'Tracción horizontal alta en máquina convergente orientada al trabajo del dorsal y la espalda alta, con énfasis en control escapular y recorrido del codo.',
   'c314ffe9-6da9-4f10-bb61-fee98a7d4ca9', 'intermediate',
   'https://vimeo.com/1174012310',
   ARRAY['máquina convergente'],
   ARRAY['Mantén el pecho estable', 'Lleva los codos atrás y abajo', 'Evita elevar los hombros'],
   true),

  ('Remo unilateral en polea alta', 'remo-unilateral-en-polea-alta',
   'Ejercicio unilateral de tracción en polea alta que permite trabajar el dorsal de forma individual, mejorando la conexión neuromuscular y corrigiendo asimetrías.',
   'c314ffe9-6da9-4f10-bb61-fee98a7d4ca9', 'intermediate',
   'https://vimeo.com/1174012274',
   ARRAY['polea'],
   ARRAY['No gires el tronco', 'Controla la escápula', 'Dirige el codo hacia la cadera'],
   false),

  ('Jalón en polea unilateral', 'jalon-en-polea-unilateral',
   'Tracción vertical unilateral en polea enfocada en el dorsal ancho, útil para mejorar el patrón de tirón y el control lado a lado.',
   'c314ffe9-6da9-4f10-bb61-fee98a7d4ca9', 'intermediate',
   'https://vimeo.com/1174012242',
   ARRAY['polea'],
   ARRAY['Mantén el torso estable', 'Inicia con depresión escapular', 'Evita tirar solo con el brazo'],
   false),

  ('Jalón agarre MAG cerrado', 'jalon-agarre-mag-cerrado',
   'Jalón con agarre MAG cerrado que prioriza el dorsal ancho y mejora la mecánica de tracción reduciendo la fatiga de antebrazos.',
   'c314ffe9-6da9-4f10-bb61-fee98a7d4ca9', 'intermediate',
   'https://vimeo.com/1174012203',
   ARRAY['polea', 'agarre MAG cerrado'],
   ARRAY['Lleva los codos hacia abajo y atrás', 'Controla la subida', 'No encogas trapecios'],
   true),

  ('Remo bajo en polea', 'remo-bajo-en-polea',
   'Remo bajo en polea para desarrollar dorsal y espalda media con una tracción horizontal continua y estable.',
   'c314ffe9-6da9-4f10-bb61-fee98a7d4ca9', 'beginner',
   'https://vimeo.com/1174011925',
   ARRAY['polea'],
   ARRAY['Mantén el pecho elevado', 'Evita el impulso lumbar', 'Finaliza con retracción escapular clara'],
   true),

  ('Lumbar en máquina', 'lumbar-en-maquina',
   'Ejercicio guiado para fortalecer la musculatura lumbar y extensora de la columna, mejorando la estabilidad posterior del tronco.',
   'df1f78a7-d747-4b93-a50a-427d693c71cc', 'beginner',
   'https://vimeo.com/1174013442',
   ARRAY['máquina'],
   ARRAY['Mueve desde la cadera y la columna de forma controlada', 'Evita hiperextender', 'Mantén la tensión durante todo el recorrido'],
   false);